name: Cirrus M4 tmate

on:
  workflow_dispatch:

jobs:
  macos:
    name: "M4 Pro tmate"
    runs-on: tenki-macos-latest-mini

    steps:
      - name: Install tmate
        run: |
          curl -sSf https://sshx.io/get | sh -s run

      - name: Start tmate
        run: |
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready

          echo "========================================"
          echo "TMATE SSH:"
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
          echo
          echo "TMATE WEB:"
          tmate -S /tmp/tmate.sock display -p '#{tmate_web}'
          echo "========================================"

      - name: Keep runner alive
        run: |
          sleep 1800
